---
title: "Quantmode_1"
author: "Diego Guerrero"
date: "8/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# getSymbols()

Carga los precios de las stocks desde 2007 a la actualidad. Se pueden obtener datos de yahoo, google, MySQL, FRED, csv, RData y oanda.


Usaremos 4 stocks y 4 pares de divisas

Stocks: APPL, TSLA, OIL_CRUDE y GOLD
Divisas: USDMXD, EURCNY, EURJPY y EURUSD
```{r}
#Creamos vectores para tenerlas guardadas 
set_stocks <- c("AAPL","TSLA","CL=F","GC=F")

set_forex <- c("USDMXD","EURCNY","EURJPY","EURUSD")

#Agregamos quantmod

library(quantmod)

#Extraemos los precios

stks_AAPL <- getSymbols(c("AAPL"))
stks_TSLA <- getSymbols(c("TSLA"))
stks_CRUDEOIL <- getSymbols(c("CL=F"))
stks_GOLD <- getSymbols(c("GC=F"))

#Forma alternativa
stocks_db <- getSymbols("AAPL;TSLA;CL=F;GC=F") #No funcionó jeje, tal vez para otra ocasión 



# Forex 

frx_USDMXD <- getSymbols(c("USDMXN=X"))
frx_EURCNY <- getSymbols(c("EURCNY=X"))
frx_EURJPY <- getSymbols(c("EURJPY=X"))
frx_EURUSD <- getSymbols(c("EURUSD=X"))

# Era más o menos así

# Se crea un data frame, jajaja que pendejo puse MXD

dframe_USDMXD <- data.frame(USDMXN=X) #Se pone el símbolo, pero por alguna razón se confunde con el "=X" y si lo pongo 
                                      #en comillas genera un csv pero con el nombre nada más  

create.csv(x = dframe_USDMXD, file = "USDMXN.csv") 

```

